#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	rmd="rm -rf" \
	mkd="mkdir -pv"

# Useful aliases
alias \
	cl="clear" \
	gu="git undo" \
	ytmp3=$'yt-dlp --verbose --output "%(artist)s - %(title)s.%(ext)s" --yes-playlist --windows-filenames --abort-on-unavailable-fragment --buffer-size 1M --extract-audio --audio-format mp3 --audio-quality 320K --embed-metadata --embed-thumbnail --download-archive _songs.txt --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'"'\
	yy="yay --noconfirm && yay -Sc --noconfirm"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lisa" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# Server
alias \
	mcct="ssh root@192.168.1.152 lxc-start 108" \
	debct="ssh root@192.168.1.152 lxc-start 109" \
	pve-update-all="ssh root@192.168.1.152 bash pve-update-all.sh"
